#include <string>


std::string simple = R"(

	#VRML V2.0 utf8

	WorldInfo {

	   title "cube.wrl"

	   info "VRML file generated by IVREAD."

	}


)";

std::string two_simple_nodes = R"(

	#VRML V2.0 utf8

	WorldInfo {

	   title "cube.wrl"

	   info "VRML file generated by IVREAD."

	}

    Group {

		geometry [ 58.5 458.02 68.78 ]

		geometry 100.001001       5.55317      -3.05561

    }


)";

std::string node_in_node = R"(

	#VRML V2.0 utf8

    Shape {
		appearance Appearence  {
			ambientIntensity  0.2
		}
	}

)";

std::string quite_deep_recursive_nodes = R"(

	#VRML V2.0 utf8

    Shape {
		appearance Appearence  {
			ambientIntensity  0.2456456
			appearance Appearence {
				lightExposure 42
			}
		}
       geometry [ 58.5 458.02 68.78 ,
                  100.001001 5.55317 -3.05561 ]
	}

    Group {
		bboxCenter 58.7E-3 0.0 15
		bboxSize   -1.0 -1.0 -1.0
	}

)";

std::string group_with_nodes_array = R"(

	#VRML V2.0 utf8

    Group {
		children [

					Group {
                           bboxCenter 58.7E-3 0.0 15
                      },

                    Group {
                           bboxSize   -1.0 -1.0 -1.0
                      }

				 ]
	}

)";

std::string simple_def = R"(

	#VRML V2.0 utf8

    Group {
		children [
					DEF id Group {
                           bboxCenter 58.7E-3 0.0 15
                      }
				 ]
	}

)";

std::string simple_use = R"(

	#VRML V2.0 utf8

    Group {
		children [
					DEF id Group {
                           bboxCenter 58.7E-3 0.0 15
                      }
				 ]
	}

	Group {

		instance USE id 
    }

)";


std::string children_with_both_USE_DEF_and_normal_type_nodes = R"(

	#VRML V2.0 utf8

    Group {
		children [
					DEF id Group {
                           bboxCenter 58.7E-3 0.0 15
                      },
					USE id,
                    Shape {
						appearance Appearence  {
							ambientIntensity  0.2
						}
					}
				 ]
	}

)";

std::string classic = R"(

	#VRML V2.0 utf8

 

  WorldInfo {

    title "cube.wrl"

    info "VRML file generated by IVREAD."

  }

 # comment

  Group {

    children [

      DEF id Group {
                      bboxCenter 58.7E-3 0.0 15
                    },
	  USE id,

      Shape {

        geometry IndexedLineSet {

          coord Coordinate {

           point [ 285.5 434.2858 8.5,
                   284.83615 434.5 8.5,
                   285.5 434.5 8.3120184,
                   283.5 436.35297 7.5,
                   283.28903 436.5 7.5,
                   283.5 436.5 7.3894577,
                   283.5 435.24545 8.5,
                   283.22855 435.5 8.5,
                   283.5 435.5 8.2797327
            ]

          }

          coordIndex [ 2, 0, 1, -1, 5, 3, 4, -1
          ]

        }

      }

    ]

  }


)";

std::string node_with_switch = R"(

	#VRML V2.0 utf8

    Group {
          children [ 
            DEF A1     Switch {
              whichChoice 0
              choice 
                DEF C2  Group { }
               }
                   ]
          }
)";

std::string node_with_boolean = R"(

	#VRML V2.0 utf8

    Group {
      shape Shape {

          geometry 
              IndexedFaceSet {
                  coordIndex [ 944, 942, 943, -1, 947, 945, 946, -1,
                      947, 949, 948, -1, 945, 947, 948, -1,
                      946, 942, 944, -1, 946, 944, 947, -1,
                      108889, 108856, 182463, -1, 108863, 108433, 182449, -1 ]
                  ccw TRUE
                  solid FALSE
                  convex TRUE
                  creaseAngle 0
          }
      }
    }
)";

std::string empty_node = R"(

    Group {
       subgroup Group {
           subsubgroup Group {}
        }
    }

)";

std::string node_with_children_array_without_brackets = R"(

    Group {
      children DEF ShowHideSep Group {
           children [ 
                DEF emptyGroup     Group {

                },
          
                DEF bpPointsInventor     Group {

                },

                DEF bpROIViewerInventorT   Group {
                  children 
                    DEF nine Switch {
                      whichChoice -1
                      choice 
                        DEF TimeSwitch10     Switch {
                          whichChoice -1
                        }
                    }
                },

                DEF bpSurfacesViewerInventor     Group {
                  children [ 
                    DEF one     Switch {
                      whichChoice 0
                      choice 
                        DEF grehgregre     Group {
                          children 
                            DEF TimeSwitch     Switch {
                              whichChoice 0
                              choice 
                                DEF bpColorSwitchSetInventor     Group {
                                  children [ 
                                    DEF htrehtr     Group {
                                      children [ 
                                        DEF hrtehteh     Shape {
                                          appearance 
                                              Appearance {
                                            material 
                                                Material {
                                              diffuseColor 0 0.80000001 0
                                            }

                                          }
                                          geometry 
                                              IndexedFaceSet {
                                            coord 
                                            DEF jnyuju     Coordinate {
                                              point [ 285.5 434.2858 8.5,
                                                  284.83615 434.5 8.5,
                                                  515.5 612.5 31.799721 ]

                                            }
                                            normal 
                                            DEF wetwt     Normal {
                                              vector [ -0.2371722 -0.7134968 -0.65929627,
                                                  0.28721604 0.440483 0.85057724 ]

                                            }
                                            coordIndex [ 2, 0, 1, -1, 5, 3, 4, -1,
                                                8, 6, 7, -1, 11, 9, 10, -1,
                                                7, 9, 11, -1, 8, 7, 11, -1,
                                                8, 11, 4, -1, 8, 4, 3, -1,
                                                14, 12, 13, -1, 5, 16, 15, -1,
                                                787, 641, 791, -1, 642, 545, 791, -1 ]
                                            ccw TRUE
                                            solid FALSE
                                            convex TRUE
                                            creaseAngle 0

                                          }

                                        },
                                  
                                        DEF seven     Shape {
                                          appearance 
                                              Appearance {
                                            material 
                                                Material {
                                              diffuseColor 0 0 0.80000001

                                            }

                                          }
                                          geometry 
                                              IndexedFaceSet {
                                            coord 
                                            USE grthg
                                            normal 
                                            USE ghhhhhyuu
                                            coordIndex [ 944, 942, 943, -1, 947, 945, 946, -1,
                                                947, 949, 948, -1, 945, 947, 948, -1,
                                                946, 942, 944, -1, 946, 944, 947, -1,
                                                108889, 108856, 182463, -1, 108863, 108433, 182449, -1 ]
                                            ccw TRUE
                                            solid FALSE
                                            convex TRUE
                                            creaseAngle 0

                                          }

                                        } ]

                                    },
                              
                                    DEF SelectionColorClass     Group {

                                    } ]

                                }

                            }

                        }

                    },
              
                    DEF ejt     Switch {
                      whichChoice -1

                    } ]

                },

               DEF bpTracksViewerInventor  Group {
                  children 
                    DEF eleven Transform {
                      translation 0 0 0
                      rotation 0 0 1 0
                    }
                }
           ]
      }
    }
)";